name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build desktop with gradle
      run: ./gradlew desktop:dist

    - uses: actions/upload-artifact@v2
      with:
        name: desktop-jar
        path: desktop/build/libs/Mindustry.jar
